# Automatically generated by brunch.
# Do not edit. Use extras.mk instead.
CFGTREE_ROOT := $(LOCAL_PATH)
include device/generic/brillo/brillo_base.mk

PRODUCT_NAME := $(call get_product_name_from_file)
ifneq ($(PRODUCT_NAME),$(call cfgtree-get,name))
  $(error config/name, <name>.mk, and AndroidProducts.mk must all be updated together.)
endif
PRODUCT_BRAND := $(call cfgtree-get,brand)
PRODUCT_DEVICE := $(call cfgtree-get,device)
PRODUCT_MANUFACTURER := $(call cfgtree-get,manufacturer)
PRODUCT_PACKAGES += $(call cfgtree-get-if-exists,packages)
# Populate PRODUCT_COPY_FILES from disk but avoid requiring the use of
# $(LOCAL_PATH) by prepending it here.
PRODUCT_COPY_FILES += $(addprefix $(LOCAL_PATH)/,$(call cfgtree-get-if-exists,copy_files))

# Expect any required sepolicies in the sepolicy path.
BOARD_SEPOLICY_DIRS := $(BOARD_SEPOLICY_DIRS) $(LOCAL_PATH)/sepolicy

# Add any extra Android product.mk directive in extras.mk
-include $(LOCAL_PATH)/extras.mk
